# Generated by Django 4.2.8 on 2024-01-08 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.TextField(verbose_name='')),
                ('theme', models.IntegerField()),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('markerCount', models.IntegerField()),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('psswd', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dateTimeCreated', models.DateTimeField()),
                ('isDeleted', models.BooleanField(default=False)),
                ('mapCount', models.IntegerField(default=0)),
                ('token', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='USER_RELATION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('usrOneId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usrRelToUser1', to='modelManager.user')),
                ('usrTwoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usrRelToUser2', to='modelManager.user')),
            ],
        ),
        migrations.CreateModel(
            name='MARKER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('address', models.CharField(max_length=40)),
                ('imageCount', models.IntegerField(default=0)),
                ('hasDesc', models.BooleanField(default=False)),
                ('dateTimeCreated', models.DateTimeField()),
                ('mapId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markerToMapId', to='modelManager.map')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markerToUserId', to='modelManager.user')),
            ],
        ),
        migrations.CreateModel(
            name='MAP_USER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('mapId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapUserToMapId', to='modelManager.map')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapUserToUserId', to='modelManager.user')),
            ],
        ),
        migrations.CreateModel(
            name='MAP_REQEST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqType', models.IntegerField()),
                ('status', models.IntegerField()),
                ('usrRel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapRequestToUserRelation', to='modelManager.user_relation')),
            ],
        ),
        migrations.CreateModel(
            name='FRIEND_REQUEST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateSent', models.DateTimeField()),
                ('recId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiverToUser', to='modelManager.user')),
                ('sendId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senderToUser', to='modelManager.user')),
            ],
        ),
    ]
